### PR TITLE
Optimize map loading time by optimizing tilematrix loading

### PR DESCRIPTION
**Pull request by rodjjo**
## What
Optimize the tile's loading time.

## Why
There was space for optimizations there.

## Notes:
This is my pull commit to optimize tile's loading time.
Things that had been done to reduce the loading time for about 20 to 25%:
* Cached several functions
* Optimize integer reading from file
* Cache from_flags functions
* Transform TileMatrix in one dimensional array and use an iterator.
* Save time using cache directly (direct access to ._CACHE attribute)

I reduced functions calls too
I my machine a small world was loading with 18s and now is loading with 14s.

What did i do to compare if everything is good ?:
```python
import sys

sys.path.append('.') # i renamed the folder and i'm usiing local module import

import lihzahrd # original
import lihzahrd2 # speed up changes renamed to test changes

world1 = lihzahrd2.World.create_from_file('TestWorld.wld')

if True: # change false to skip testing
    print('loading world to compare')
    world2 = lihzahrd.World.create_from_file('TestWorld.wld')

    print('comparing')
    for x in range(world1.tiles.size.x):
        for y in range(world1.tiles.size.y):
            tile1 = world1.tiles[(x, y)]
            tile2 = world2.tiles[(x, y)]
            assert (tile1.block is None) == (tile2.block is None)
            assert (tile1.wall is None) == (tile2.wall is None)
            assert (tile1.liquid is None) == (tile2.liquid is None)
            assert (tile1.wiring is None) == (tile2.wiring is None)

            if tile1.block:
                assert tile1.block.type == tile2.block.type
                assert tile1.block.shape == tile2.block.shape
                assert tile1.block.paint == tile2.block.paint
                assert tile1.block.is_active == tile2.block.is_active
                assert (tile1.block.frame is None) == (tile2.block.frame is None)
                if tile1.block.frame:
                    assert tile1.block.frame.frame_x == tile2.block.frame.frame_x
                    assert tile1.block.frame.frame_y == tile2.block.frame.frame_y

            if tile1.wall:
                assert tile1.wall.type == tile2.wall.type
                assert tile1.wall.paint == tile2.wall.paint

            if tile1.liquid:
                assert tile1.liquid.type == tile2.liquid.type
                assert tile1.liquid.volume == tile2.liquid.volume

            if tile1.wiring and False:
                assert tile1.wiring.red == tile2.wiring.red
                assert tile1.wiring.green == tile2.wiring.green
                assert tile1.wiring.blue == tile2.wiring.blue
                assert tile1.wiring.yellow == tile2.wiring.yellow
                assert tile1.wiring.actuator == tile2.wiring.actuator
```

### CODE REVIEW

**Comment by rodjjo** [comment]
I squashed my commits before create the pull request.

**Comment by Steffo99** [comment]
SORRY!

I didn't notice this pull request until now D:

I'll check it ASAP :)

In the meantime, thanks for your contribution!

**Comment by Steffo99** [comment]
I merged your tree with the new changes from the `1.4` branch.

I am getting a ~2 second improvement on world parsing on PyPy, so the optimization is working! :D

However, I would like to work a bit on code readibility before merging ^^

**Comment by rodjjo** [comment]
Ok, i was waitng for next optimizations.

**Pull request closed without merging**
